apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: access-cloudyuga
spec:
  destination:
    name: reviews
  precedence: 2
  match:
    request:
      headers:
        cookie:
          regex: "^(.*?;)?(user=cloudyuga)(;.*)?$"
  route:
  - labels:
      version: v2
