apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: split2
spec:
  destination:
    name: reviews
  precedence: 1
  route:
  - labels:
      version: v2
    weight: 50
  - labels:
      version: v3
    weight: 50
