apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: cloudyuga-csr
spec:
  groups:
  - system:authenticated
  request: 
  usages:
  - digital signature
  - key encipherment
  - client auth
