
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-manager-binding
subjects:
- kind: User
  name: nkhare # This allow manager to read any secrete present in all the namespaces
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cluster-manager
  apiGroup: ""k
